apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: myingress
spec:
  rules:
  - host: omarapp.com
    http:
      paths:
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: ba-service
              port:
                number: 3001
        - path: /
          pathType: Prefix
          backend:
            service:
              name: fr-service
              port:
                number: 80
